from pathlib import Path
ROOT=Path('/mnt/data/moncv20')

langs={
'fr':{'home':'Accueil','formation':'Formation','exp':'Expériences','domains':'Domaines','cert':'Certificats','interests':'Centres d’intérêt','contact':'Contact','lang':'FR','hero':'Mountaga TALL','tag':'MARKETING • COMMERCIAL • TECHNIQUE • FORMATION','lead':'Profil professionnel multidisciplinaire, à l’intersection de la relation client, du développement commercial, du marketing, du support technique et de la formation.','cta':'Me contacter','explore':'Parcourir le parcours','about':'Un profil hybride, orienté terrain et transformation','aboutp':'Une expérience internationale construite entre France, Portugal, Espagne et Côte d’Ivoire, avec un fil rouge : comprendre les besoins, structurer les opérations et faire avancer les équipes.','quick':'COMPÉTENCES CLÉS','skills':['Marketing','Développement commercial','Gestion de projet','Veille informationnelle','Support technique','Management'],'contactLead':'Disponible pour des opportunités, missions et collaborations à fort impact.','phone':'+225 07 78 61 58 61','email':'mountaga.tall@gmail.com'},
'en':{'home':'Home','formation':'Education','exp':'Experience','domains':'Areas','cert':'Certificates','interests':'Interests','contact':'Contact','lang':'EN','hero':'Mountaga TALL','tag':'MARKETING • SALES • TECHNICAL • TRAINING','lead':'Multidisciplinary professional profile at the crossroads of customer relations, business development, marketing, technical support and training.','cta':'Contact me','explore':'Explore my background','about':'A hybrid profile built for field execution and transformation','aboutp':'International experience across France, Portugal, Spain and Côte d’Ivoire, with a consistent focus: understand needs, structure operations and help teams move forward.','quick':'KEY SKILLS','skills':['Marketing','Business development','Project management','Information monitoring','Technical support','Management'],'contactLead':'Open to opportunities, assignments and high-impact collaborations.','phone':'+225 07 78 61 58 61','email':'mountaga.tall@gmail.com'},
'es':{'home':'Inicio','formation':'Formación','exp':'Experiencia','domains':'Áreas','cert':'Certificados','interests':'Intereses','contact':'Contacto','lang':'ES','hero':'Mountaga TALL','tag':'MARKETING • COMERCIAL • TÉCNICO • FORMACIÓN','lead':'Perfil profesional multidisciplinario en la intersección de atención al cliente, desarrollo comercial, marketing, soporte técnico y formación.','cta':'Contactarme','explore':'Ver mi trayectoria','about':'Un perfil híbrido orientado al terreno y a la transformación','aboutp':'Experiencia internacional entre Francia, Portugal, España y Costa de Marfil, con un hilo conductor: entender las necesidades, estructurar operaciones y hacer avanzar a los equipos.','quick':'COMPETENCIAS CLAVE','skills':['Marketing','Desarrollo comercial','Gestión de proyectos','Inteligencia informativa','Soporte técnico','Management'],'contactLead':'Disponible para oportunidades, misiones y colaboraciones de alto impacto.','phone':'+225 07 78 61 58 61','email':'mountaga.tall@gmail.com'}
}

def nav(l):
 x=langs[l]; other={'fr':'en','en':'es','es':'fr'}[l]
 return f'''<header class="site-header"><div class="container nav"><a class="brand" href="./"><div class="mark">MT</div><div><strong>MONCV20</strong><small>MOUNTAGA TALL</small></div></a><div class="lang"><a class="active" href="../{l}/">{l.upper()}</a><a href="../{other}/">{other.upper()}</a></div><button class="menu" aria-expanded="false">☰</button><nav class="main-nav"><a href="../{l}/">{x['home']}</a><a href="../{l}/formation/">{x['formation']}</a><a href="../{l}/experiences/">{x['exp']}</a><a href="../{l}/domaines/">{x['domains']}</a><a href="../{l}/certificats/">{x['cert']}</a><a href="../{l}/interets/">{x['interests']}</a><a href="../{l}/contact/">{x['contact']}</a></nav></div></header>'''

def footer(l): return f'''<footer class="footer"><div class="container footer-inner"><span>© <span class="year"></span> Mountaga TALL · MonCV20</span><span><a href="../fr/">FR</a> · <a href="../en/">EN</a> · <a href="../es/">ES</a></span></div></footer><script src="../script.js"></script>'''

def shell(l,title,body): return f'''<!doctype html><html lang="{l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#48b8ff"><meta name="description" content="MonCV20 — Mountaga TALL"><link rel="stylesheet" href="../styles.css"><link rel="manifest" href="../manifest.json"><title>{title}</title></head><body>{nav(l)}{body}{footer(l)}</body></html>'''

def home(l):
 x=langs[l]
 cards=[(x['formation'],'01','../formation/'),(x['exp'],'02','../experiences/'),(x['domains'],'03','../domaines/'),(x['cert'],'04','../certificats/'),(x['interests'],'05','../interets/'),(x['contact'],'06','../contact/')]
 c=''.join(f'<a class="card reveal" href="{u}"><span class="number">{n}</span><h3>{name}</h3><p>↗</p></a>' for name,n,u in cards)
 return shell(l,f"MonCV20 — {x['hero']}",f'''<main><section class="hero"><div class="container hero-grid"><div class="reveal"><span class="eyebrow">{x['tag']}</span><h1>{x['hero']}<br><span>MonCV20</span></h1><p>{x['lead']}</p><div class="hero-actions"><a class="btn btn-primary" href="mailto:{x['email']}">{x['cta']} ↗</a><a class="btn btn-ghost" href="../{l}/experiences/">{x['explore']}</a></div><div class="stats"><div class="stat"><strong>10+</strong><span>{x['exp']}</span></div><div class="stat"><strong>4</strong><span>{x['domains']}</span></div><div class="stat"><strong>3</strong><span>FR · EN · ES</span></div></div></div><div class="profile-card reveal"><div class="profile-orb">MT</div><h2>Mountaga TALL</h2><div class="profile-meta">34 ans · {"Abidjan, Côte d’Ivoire" if l=='fr' else "Abidjan, Côte d’Ivoire"}</div><div class="chips">{''.join(f'<span class="chip">{s}</span>' for s in x['skills'])}</div></div></div></section><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">{x['quick']}</span><h2>{x['about']}</h2></div><p>{x['aboutp']}</p></div><div class="grid grid-3">{c}</div></div></section><section class="section"><div class="container"><div class="cta"><div><span class="eyebrow">{x['contact']}</span><h2>{x['contactLead']}</h2><p>{x['email']} · {x['phone']}</p></div><a class="btn btn-primary" href="../{l}/contact/">{x['cta']} ↗</a></div></div></section></main>''')

edu=[
('EMB Business School','BTS NRC — Négociation Relation Client','2012–2014','Business Accounting Administration & Customer Relationship'),
("Merin's",'Électro-Mécanique, Électronique & Mécanique de véhicules','2018–2019','Voitures · Motos · Bateaux'),
('Université Paris-Est Créteil (UPEC)','Langues Étrangères, Littératures & Civilisations','2011–2012','Anglais & Espagnol'),
('IFHS Sécurité','SSIAP 1 — Sécurité incendie','2016','Sécurité incendie'),
('IESC FORMATION','Titre V APS / CQP APS','2015','Sécurité des biens et des personnes')]

exp=[
('Amore','Superviseur / Responsable marketing','Abidjan, Côte d’Ivoire','Fév. 2020 – Présent',['Organisation et optimisation des chaînes d’opérations','Veille informationnelle','Repérage de la résistance à la transformation digitale','Supervision du service','Gestion des livraisons','Négociation et signature de contrats partenaires','Meetings avec les chefs de départements','Création et organisation des plannings']),
('Dragon Investors','Technical Sales Manager','Barcelone, Espagne','Mai 2019 – Fév. 2020',['Inbound & outbound sales pour Engie, Eni, Planète Oui, Butagaz, Free, SFR','Qualification de leads et vente']),
('Tiller Systems','Customer Technical Support Manager','Région de Barcelone, Espagne','Juin 2018 – Fév. 2019',['Assistance chat & téléphone','Installation hardware','Création et configuration de comptes','Troubleshooting','Formation','Reporting & optimisation des méthodes de travail','Qualité & KPI','Digitalisation','Création et évolution de sites internes']),
('French Language Trainer','Formateur de français','Région de Barcelone, Espagne','Juin 2018 – Fév. 2019',['Cours de français aux collègues']),
('Airbus','Technical Support & Procurement Supervisor','Barcelone, Espagne','Déc. 2017 – Avr. 2018',['Commandes groupées internes','Gestion fournisseurs','Account management pour acheteurs Airbus Internals','CRM','Gestion des achats']),
('Google Hardware Technical Tiers','Support technique Tier II','Barcelone, Espagne','Nov. 2016 – Nov. 2017',['Support IT à distance et sur site','Point de contact prestataire IT local','Diagnostic et résolution de problèmes PC / logiciels / communications','Installation et remplacement de systèmes et périphériques','Documentation complète du ticketing']),
('Bouygues Telecom','Customer Service Trainer','Lisbonne, Portugal','Sept. 2015 – Oct. 2016',['Analyse des écarts de compétences IT','Conception de manuels techniques simples','Formation sur outils et programmes','Méthodes pédagogiques & gamification','Formation des nouveaux employés','Sensibilisation à la sécurité','Évaluation des sessions','Mise à jour des supports']),
('Free Jobs','Customer Service Counsellor','Région de Paris, France','Nov. 2014 – Juin 2015',['Identification des besoins et orientation des appels','Information clients','Promotion des services','Proposition de services adaptés','Troubleshooting']),
('SARL SIVEA','HR & Recruitment Director','Paris, France','Août 2013 – Nov. 2014',['Recrutement, screening, entretiens et placement','Sélection des CV','Définition des besoins avec les managers recruteurs','Paie, absences, remplacements']),
('AUTOBACS FRANCE','Car Electronician & Technical Sales Manager','Bonneuil-sur-Marne, France','Sept. 2011 – Août 2013',['Vente et installation audio Bluetooth / USB et accessoires','Spécialiste audio & vidéo automobile','Connectivité, conseil et installation atelier','Vente & après-vente'])]

trans={
'fr':{'edu':'Formations & diplômes','exp':'Expériences professionnelles','domains':'Domaines d’expertise','cert':'Certificats Web','interests':'Centre d’intérêts','contact':'Contact','read':'Voir le parcours','native':'Natif / bilingue','training':'Langues & formation','commercial':'Commercial','technical':'Technique','restaurant':'Restauration & restauration rapide','security':'Sécurité','logistic':'Logistique','web':'Marketing digital & web','languages':'Langues','interestsText':'Marketing, développement commercial, gestion de projet, veille informationnelle, support technique et management.'},
'en':{'edu':'Education & degrees','exp':'Professional experience','domains':'Areas of expertise','cert':'Web certificates','interests':'Interests','contact':'Contact','read':'View background','native':'Native / bilingual','training':'Languages & training','commercial':'Sales','technical':'Technical','restaurant':'Food service & fast food','security':'Security','logistic':'Logistics','web':'Digital marketing & web','languages':'Languages','interestsText':'Marketing, business development, project management, information monitoring, technical support and management.'},
'es':{'edu':'Formación y diplomas','exp':'Experiencia profesional','domains':'Áreas de especialización','cert':'Certificados web','interests':'Centro de intereses','contact':'Contacto','read':'Ver trayectoria','native':'Nativo / bilingüe','training':'Idiomas y formación','commercial':'Comercial','technical':'Técnico','restaurant':'Restauración y comida rápida','security':'Seguridad','logistic':'Logística','web':'Marketing digital y web','languages':'Idiomas','interestsText':'Marketing, desarrollo comercial, gestión de proyectos, inteligencia informativa, soporte técnico y management.'}}

def formation(l):
 t=trans[l]; rows=''.join(f'<article class="timeline-item reveal"><div class="timeline-top"><div><h3>{a}</h3><div class="where">{b}</div></div><div class="period">{c}</div></div><p>{d}</p></article>' for a,b,c,d in edu)
 return shell(l,t['edu'],f'<main><div class="container breadcrumbs">MonCV20 / {t["edu"]}</div><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">FORMATION</span><h2>{t["edu"]}</h2></div></div><div class="timeline">{rows}</div></div></section></main>')

def experiences(l):
 t=trans[l]
 rows=[]
 for a,b,c,d,items in exp:
  title=b;where=c;period=d
  if l=='en': title_map={'Superviseur / Responsable marketing':'Marketing Supervisor / Manager','Technical Sales Manager':'Technical Sales Manager','Customer Technical Support Manager':'Customer Technical Support Manager','Formateur de français':'French Language Trainer','Technical Support & Procurement Supervisor':'Technical Support & Procurement Supervisor','Support technique Tier II':'Tier II Technical Support','Customer Service Trainer':'Customer Service Trainer','Customer Service Counsellor':'Customer Service Counsellor','HR & Recruitment Director':'HR & Recruitment Director','Car Electronician & Technical Sales Manager':'Car Electronician & Technical Sales Manager'}; title=title_map.get(title,title)
  elif l=='es': title_map={'Superviseur / Responsable marketing':'Supervisor / Responsable de marketing','Formateur de français':'Formador de francés','Support technique Tier II':'Soporte técnico Tier II','Customer Service Trainer':'Formador de atención al cliente','Customer Service Counsellor':'Asesor de atención al cliente'}; title=title_map.get(title,title)
  rr={'en':'Experience','es':'Experiencia'}.get(l,'Expérience')
  lis=''.join(f'<li>{it}</li>' for it in items)
  rows.append(f'<article class="timeline-item reveal"><div class="timeline-top"><div><h3>{a}</h3><div class="where">{title} · {where}</div></div><div class="period">{period}</div></div><ul class="list">{lis}</ul></article>')
 return shell(l,t['exp'],f'<main><div class="container breadcrumbs">MonCV20 / {t["exp"]}</div><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">CAREER</span><h2>{t["exp"]}</h2></div></div><div class="timeline">{"".join(rows)}</div></div></section></main>')

def domains(l):
 t=trans[l]; data=[('💼',t['commercial'],{'fr':'Développement commercial, vente, négociation de contrats, qualification de leads et relation partenaires.','en':'Business development, sales, contract negotiation, lead qualification and partner relations.','es':'Desarrollo comercial, ventas, negociación de contratos, cualificación de leads y relación con socios.'}[l]),('⚙️',t['technical'],{'fr':'Support technique, électronique, troubleshooting, installation, configuration et optimisation.','en':'Technical support, electronics, troubleshooting, installation, configuration and optimization.','es':'Soporte técnico, electrónica, resolución de problemas, instalación, configuración y optimización.'}[l]),('🍽️',t['restaurant'],{'fr':'Expérience professionnelle et opérationnelle dans des environnements de service et d’exploitation.','en':'Professional and operational experience in service and operations environments.','es':'Experiencia profesional y operativa en entornos de servicio y operaciones.'}[l]),('🛡️',t['security'],{'fr':'SSIAP 1, APS/CQP APS et expérience de sensibilisation aux enjeux de sécurité.','en':'SSIAP 1, APS/CQP APS and experience with security awareness topics.','es':'SSIAP 1, APS/CQP APS y experiencia en temas de sensibilización sobre seguridad.'}[l]),('🚚',t['logistic'],{'fr':'Gestion des livraisons, achats, fournisseurs, commandes et coordination opérationnelle.','en':'Delivery management, procurement, suppliers, orders and operational coordination.','es':'Gestión de entregas, compras, proveedores, pedidos y coordinación operativa.'}[l]),('🌐',t['web'],{'fr':'Digitalisation, création de sites internes et marchands, réseaux sociaux, process et stratégie.','en':'Digitalization, internal and e-commerce websites, social media, processes and strategy.','es':'Digitalización, sitios web internos y comerciales, redes sociales, procesos y estrategia.'}[l])]
 cards=''.join(f'<article class="service reveal"><div class="icon">{i}</div><h3>{n}</h3><p>{p}</p></article>' for i,n,p in data)
 return shell(l,t['domains'],f'<main><div class="container breadcrumbs">MonCV20 / {t["domains"]}</div><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">EXPERTISE</span><h2>{t["domains"]}</h2></div></div><div class="service-list">{cards}</div></div></section></main>')

def certificates(l):
 t=trans[l]
 body={'fr':'Google Digital Learning — Certification en Marketing Digital de Google · Lancez une campagne de publicité avec Google AdWords · Naviguez en sécurité sur Internet · Comprendre le Web. OpenClassrooms — Modules de formation validés en ligne.','en':'Google Digital Learning — Google Digital Marketing certification · Launch a Google Ads campaign · Browse the Internet safely · Understand the Web. OpenClassrooms — Validated online training modules.','es':'Google Digital Learning — Certificación de Marketing Digital de Google · Lanzar una campaña publicitaria con Google Ads · Navegar de forma segura en Internet · Comprender la Web. OpenClassrooms — Módulos de formación online validados.'}[l]
 return shell(l,t['cert'],f'<main><div class="container breadcrumbs">MonCV20 / {t["cert"]}</div><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">CERTIFICATIONS</span><h2>{t["cert"]}</h2></div></div><div class="grid grid-2"><article class="card reveal"><span class="number">GOOGLE</span><h3>Google Digital Learning</h3><p>{body.split(" OpenClassrooms")[0]}</p></article><article class="card reveal"><span class="number">OPENCLASSROOMS</span><h3>OpenClassrooms</h3><p>{body.split("OpenClassrooms")[-1].lstrip(' —')}</p></article></div></div></section></main>')

def interests(l):
 t=trans[l]
 langtext={'fr':'Français · Anglais · Espagnol','en':'French · English · Spanish','es':'Francés · Inglés · Español'}[l]
 return shell(l,t['interests'],f'<main><div class="container breadcrumbs">MonCV20 / {t["interests"]}</div><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">PROFILE</span><h2>{t["interests"]}</h2></div></div><div class="grid grid-2"><article class="card reveal"><span class="number">{t["languages"]}</span><h3>{langtext}</h3><p>{t["native"]}</p></article><article class="card reveal"><span class="number">KEY SKILLS</span><h3>{t["web"]}</h3><p>{t["interestsText"]}</p></article></div></div></section></main>')

def contact(l):
 x=langs[l]
 return shell(l,x['contact'],f'<main><div class="container breadcrumbs">MonCV20 / {x["contact"]}</div><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">LET’S CONNECT</span><h2>{x["contactLead"]}</h2></div></div><div class="contact-grid"><article class="contact-box reveal"><span class="number">EMAIL</span><h3>{x["email"]}</h3><p>Mail</p><p><a href="mailto:{x["email"]}">{x["email"]}</a></p></article><article class="contact-box reveal"><span class="number">PHONE / WHATSAPP</span><h3>{x["phone"]}</h3><p>WhatsApp · Appel</p><p><a href="https://wa.me/2250778615861" target="_blank" rel="noopener">WhatsApp ↗</a></p></article></div></div></section></main>')

for l in langs:
 for path,fn in [('index.html',home),('formation/index.html',formation),('experiences/index.html',experiences),('domaines/index.html',domains),('certificats/index.html',certificates),('interets/index.html',interests),('contact/index.html',contact)]:
  p=ROOT/l/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(fn(l),encoding='utf-8')
